# Generated by Django 3.1.2 on 2020-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_userorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.IntegerField()),
                ('specfications', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
