# Generated by Django 3.1.2 on 2020-11-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterModel',
            new_name='LoginModel',
        ),
    ]
